name: 部署交互式图表到 GitHub Pages

on:
  # 当推送到 main 分支且 docs/ 目录有变化时触发
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'covid_only_updated_surveillance_data.csv'
      - 'generate_interactive_plot.py'
  
  # 允许手动触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一次部署并发
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          pip install pandas plotly

      - name: 生成交互式图表
        run: |
          python generate_interactive_plot.py

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

